In [2]:
import numpy as np

In [3]:
#create an array
a= np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
#more than one dimenstion array
b= np.array([[1,2,3],[4,5,6]])
b
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#minimum dimenstions
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [18]:
#data type 
a= np.array([1,2,3,4,],dtype=int)
print(a)

[1 2 3 4]


In [20]:
a= np.array([1,2,3,4,],dtype=int)
print(a)

[1 2 3 4]


In [24]:
a= np.array([1,2,3,4,],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [23]:
a= np.array([1,2,3,4,],dtype=float)
print(a)


[1. 2. 3. 4.]


In [29]:
a= np.array([1,2,3,4,],dtype=bool)
print(a)

[ True  True  True  True]


# data types

In [32]:
#using the array scalar type
import numpy as np
dt = np.dtype(np.int8)
print(dt)
dt1 = np.dtype(np.int16)
print(dt1)
dt2 = np.dtype(np.int32)
print(dt2)
dt3 = np.dtype(np.int64)
print(dt3)

int8
int16
int32
int64


In [34]:
#int8 , int16, int32, int64, can be replaced by equivalent srting "i1","i2","i4" etc.
dt1= np.dtype ('i1')
print(dt1)
dt2 = np.dtype('i2')
print(dt2)
dt3 = np.dtype("i4")
print(dt3)

int8
int16
int32


In [37]:
#using endian notations
import numpy as np
dt = np.dtype('>i4')
print(dt)

>i4


In [38]:
#using endian notations
import numpy as np
dt = np.dtype('<i4')
print(dt)

int32


In [40]:
#using endian notations
import numpy as np
dt = np.dtype('=<i4')
print(dt)

TypeError: data type "=<i4" not understood

In [46]:
#first create the structure data type 
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [47]:
#now apply it to ndarray object
import numpy as np
dt = np.dtype([("age",np.int8)])
a = np.array([(10,),(20,),(30,)],dtype= dt)
print(a)

[(10,) (20,) (30,)]


In [48]:
#file name can be used to access content of age column
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype= dt)
print(a['age'])


[10 20 30]


In [50]:
student = np.dtype([('name','S20'),('age',"i1"),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [54]:
student = np.dtype([('name','S20'),('age',"i1"),('marks','f4')])
a= np.array([('abc',21,50),('xyz',18,75)],dtype=student)

print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


# numpy- array attributes

### ndarraay.shape

In [61]:

import numpy as np
a =np.array([[1,2,3],[4,5,6]])
#a.shape
x=a.shape
print(x)
print("2 rows and 3 columns")

(2, 3)
2 rows and 3 columns


In [66]:
#this resize the ndarray
a= np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)
print("here we change the 2 by 3 matrix into 3 by 2 matrix")

[[1 2]
 [3 4]
 [5 6]]
here we change the 2 by 3 matrix into 3 by 2 matrix


In [69]:
#reshape function to reshape size of array
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
print(a)
b= a.reshape(3,2)
print(b)
print("change 2x3 into 3x2")

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
change 2x3 into 3x2


### ndarray.ndim : this array attribute returns the number of dimenstions

In [71]:
#an arrya of evenly spaced
import numpy as np 
a = np.arange(24)
print(a)
print('this is one dimentional array')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
this is one dimentional array


In [76]:
#This is one dimenstional array
a = np.arange(24)
print(a.ndim)

#now reshape it
b= a.reshape(2,4,3)
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### numpy.itemsize :-returns the length od each element of array in bytes

In [2]:
#dtype of array is int8 (1 byte)
import numpy as np
x = np.array([1,2,3,4,5],dtype= np.int8)
print(x.itemsize)

1


In [5]:
#dtype of array is now float32 (4 bytes )
import numpy as np
x= np.array([1,2,3,4,5],dtype=np.float32)
print(x.itemsize)

4


### numpy.flags :- its current values are returned by this functions

In [7]:
import numpy as np
x= np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# numpy-Array Creations Routines

A new ndarray object can be constructed by any of the following array routiness or using any level ndarray constructor

### numpy.empty:-it creates an unintialized array of specified shape and dtype

numpy.empty(shape, dtype=float ,order='C' )

In [12]:
import numpy as np 
x=np.empty([3,2],dtype=int)
print(x)

[[-622178384        366]
 [         0          0]
 [         1          0]]


The elements in the array shows the random values as they are not initialized

### numpy.zeros: returns a new array of specified size ,filled with zeros

numpy.zeros(shape, dtype=float ,order='C' )

In [13]:
import numpy as np
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [16]:
import numpy as np 
x= np.zeros((5,),dtype=int) #dtype=np.int also given
print(x)


[0 0 0 0 0]


In [17]:
import numpy as np
x= np.zeros((2,2),dtype=[("x","i4"),("y","i4")])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


### numpy.ones :- returns a new array of specified size ,filled with ones

numpy.ones(shape, dtype=float ,order='C' )

In [24]:
import numpy as np
x=np.ones([5,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
import numpy as np
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


# Numpy-Array From Existing Data

### How to create an array from existing data

In [ ]:
numpy.asarray:- 

numpy.asarray(shape, dtype=float ,order='C' )

In [34]:
#converting list to ndarry
import numpy as np
x= [1,2,3]
a= np.asarray(x)
print(a)

[1 2 3]


In [33]:
#dtype is set
import numpy as np
x= [1,2,3]
a= np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [36]:
#converting tuple to ndarray
import numpy as np
x= (1,2,3)
a= np.asarray(x)
print(a)

[1 2 3]


In [37]:
#ndarray from list of tuples
x= [(1,2,3),(4,5,6)]
a= np.asarray(x)
print(x)

[(1, 2, 3), (4, 5, 6)]


### numpy.frombuffer

In [44]:
import numpy as np
s= "hello world"
a=np.frombuffer(s,dtype=int)
print(a)

AttributeError: 'str' object has no attribute '__buffer__'

numpy.fromiter:This builds an ndarray from any iterable object

In [51]:
#create a list object using range function
import numpy as np
list= range(5)
list

range(0, 5)

In [52]:
#ob tain the iterator object from list 
import numpy np
list = range(5)
it = iter(list)

#use iterator to create ndarray
x=np.fromiter(it, dtype=float)
print(x)

SyntaxError: invalid syntax (<ipython-input-52-6df6a51465c7>, line 2)

# Numpy-Array From Numerical Range

### numpy.arrang :returns an ndarraay containing evenly spaced values a given range

np.arrang(start ,stop, step,dtype)

In [54]:
import numpy as np
x= np.arange (5)
print(x)

[0 1 2 3 4]


In [55]:
import numpy as np
x= np.arange (5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [57]:
import numpy as np
x= np.arange(10,20,2)
print(x)

[10 12 14 16 18]


numpy.linspace : returns the number od evenly spaced vallues between the interval is specified

np.linsapce(start ,stop ,number ,endpoint , retstep,dtype)

In [58]:
import numpy as np
x= np.linspace(10,20 ,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [59]:
#endpoint set to false
import numpy as np
x= np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [63]:
import numpy as np
x= np.linspace(1,2,3, retstep=True)
print(x)
print("retstep here is 0.25")

(array([1. , 1.5, 2. ]), 0.5)
retstep here is 0.25


### numpy.logspace : returns evenly spaced on log scale.usually base 10

numpy.logspace(start,stop,number ,endpoint,dtype)

In [67]:
import numpy as np
#default base is 10
a= np.logspace(1.0,2.0,num=10)
print(a)
    

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [68]:
#set base of the log space to 2
import numpy as np
x=np.logspace(1,10,num=10,base=2)
print(x)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
